from abc import ABC, abstractmethod

from groq import Groq

from app.core.config import settings


class LLMProvider(ABC):
    """Abstract interface for all LLM providers."""

    @abstractmethod
    def generate(self, prompt: str) -> str:
        """Generate text from a prompt."""
        raise NotImplementedError


class MockLLMProvider(LLMProvider):
    """Temporary provider used during development and testing."""

    def generate(self, prompt: str) -> str:
        return "Improved resume content generated by the mock provider."


class GroqProvider(LLMProvider):
    """Groq-backed LLM provider."""

    def __init__(self) -> None:
        self.client = Groq(
            api_key=settings.groq_api_key,
        )

    def generate(self, prompt: str) -> str:
        try:
            response = self.client.chat.completions.create(
                model=settings.groq_model,
                messages=[
                    {
                        "role": "user",
                        "content": prompt,
                    }
                ],
                temperature=0.3,
                max_completion_tokens=4000,
                timeout=60.0,
            )

            content = response.choices[0].message.content

            if not content:
                raise RuntimeError("Groq returned an empty response")

            return content.strip()

        except Exception as exc:
            raise RuntimeError(
                f"AI provider request failed: {exc}"
            ) from exc