services:
  postgres:
    image: postgres:18
    container_name: ai-resume-builder-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ai_resume_builder
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
     - postgres_data:/var/lib/postgresql
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U postgres -d ai_resume_builder"
        ]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-resume-builder-backend
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      APP_NAME: ${APP_NAME}
      APP_ENV: ${APP_ENV}
      DATABASE_URL: ${DOCKER_DATABASE_URL}
      SECRET_KEY: ${SECRET_KEY}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES:-60}
      GROQ_API_KEY: ${GROQ_API_KEY}
      GROQ_MODEL: ${GROQ_MODEL}
      FRONTEND_BASE_URL: http://host.docker.internal:5173
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads

volumes:
  postgres_data: